source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FPRealm_Example', :exclusive => true do
  pod "FPRealm", :path => "../"
end

target 'FPRealm_Tests', :exclusive => true do
  pod "FPRealm", :path => "../"

  
end
